### ISSUE TITLE
[Feat] 오늘의집 홈뷰 UI 구현

### ISSUE THREAD

**Issue by frohsch** [SOPT-32ND-APP2-Myhouse/Myhouse_iOS#13]
## 🛠 Issue
상단 뷰 구현하기
오늘의 딜 섹션 구현하기
베스트셀러 섹션 구현하기
하단 Footer 구현하기
더보기 버튼 text 변경하기 

## 📝 To-do

- [x] 상단 뷰 구현하기
- [x] 오늘의 딜 섹션 구현하기
- [x] 베스트셀러 섹션 구현하기
- [x] 하단 섹션 구현하기
- [x] Cell Footer 더보기 버튼 text 변경하기 
- [x] Cell Header 더보기, 업체 찾기 등 버튼 구현하기
