### ISSUE TITLE
[Feat] 홈뷰 API 연결

### ISSUE THREAD

**Issue by frohsch** [SOPT-32ND-APP2-Myhouse/Myhouse_iOS#39]
## 🛠 Issue

홈 뷰 API 연결

## 📝 To-do

- [ ] 베스트 상품 상품 카테고리별 보기 API 연결
- [ ] 이주의 인기 컨텐츠 API 연결
- [x] nickname을 위한 추천 집들이 API 연결

아자자ㅏ !!!!
